# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc.proto',
  package='protos',
  syntax='proto3',
  serialized_options=b'Z\007protopb',
  serialized_pb=b'\n\trpc.proto\x12\x06protos\"1\n\x08Greeting\x12\x12\n\nfirst_name\x18\x01 \x01(\t\x12\x11\n\tlast_name\x18\x02 \x01(\t\"2\n\x0cGreetRequest\x12\"\n\x08greeting\x18\x01 \x01(\x0b\x32\x10.protos.Greeting\"\x1f\n\rGreetResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\";\n\x15GreetManyTimesRequest\x12\"\n\x08greeting\x18\x01 \x01(\x0b\x32\x10.protos.Greeting\"(\n\x16GreetManyTimesResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"6\n\x10LongGreetRequest\x12\"\n\x08greeting\x18\x01 \x01(\x0b\x32\x10.protos.Greeting\"#\n\x11LongGreetResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\":\n\x14GreetEveryoneRequest\x12\"\n\x08greeting\x18\x01 \x01(\x0b\x32\x10.protos.Greeting\"\'\n\x15GreetEveryoneResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xb2\x02\n\x0cGreetService\x12\x36\n\x05Greet\x12\x14.protos.GreetRequest\x1a\x15.protos.GreetResponse\"\x00\x12S\n\x0eGreetManyTimes\x12\x1d.protos.GreetManyTimesRequest\x1a\x1e.protos.GreetManyTimesResponse\"\x00\x30\x01\x12\x41\n\x06LGreet\x12\x18.protos.LongGreetRequest\x1a\x19.protos.LongGreetResponse\"\x00(\x01\x12R\n\rGreetEveryone\x12\x1c.protos.GreetEveryoneRequest\x1a\x1d.protos.GreetEveryoneResponse\"\x00(\x01\x30\x01\x42\tZ\x07protopbb\x06proto3'
)




_GREETING = _descriptor.Descriptor(
  name='Greeting',
  full_name='protos.Greeting',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first_name', full_name='protos.Greeting.first_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_name', full_name='protos.Greeting.last_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=70,
)


_GREETREQUEST = _descriptor.Descriptor(
  name='GreetRequest',
  full_name='protos.GreetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='protos.GreetRequest.greeting', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=122,
)


_GREETRESPONSE = _descriptor.Descriptor(
  name='GreetResponse',
  full_name='protos.GreetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='protos.GreetResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=155,
)


_GREETMANYTIMESREQUEST = _descriptor.Descriptor(
  name='GreetManyTimesRequest',
  full_name='protos.GreetManyTimesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='protos.GreetManyTimesRequest.greeting', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=216,
)


_GREETMANYTIMESRESPONSE = _descriptor.Descriptor(
  name='GreetManyTimesResponse',
  full_name='protos.GreetManyTimesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='protos.GreetManyTimesResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=258,
)


_LONGGREETREQUEST = _descriptor.Descriptor(
  name='LongGreetRequest',
  full_name='protos.LongGreetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='protos.LongGreetRequest.greeting', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=260,
  serialized_end=314,
)


_LONGGREETRESPONSE = _descriptor.Descriptor(
  name='LongGreetResponse',
  full_name='protos.LongGreetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='protos.LongGreetResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=351,
)


_GREETEVERYONEREQUEST = _descriptor.Descriptor(
  name='GreetEveryoneRequest',
  full_name='protos.GreetEveryoneRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='greeting', full_name='protos.GreetEveryoneRequest.greeting', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=353,
  serialized_end=411,
)


_GREETEVERYONERESPONSE = _descriptor.Descriptor(
  name='GreetEveryoneResponse',
  full_name='protos.GreetEveryoneResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='protos.GreetEveryoneResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=413,
  serialized_end=452,
)

_GREETREQUEST.fields_by_name['greeting'].message_type = _GREETING
_GREETMANYTIMESREQUEST.fields_by_name['greeting'].message_type = _GREETING
_LONGGREETREQUEST.fields_by_name['greeting'].message_type = _GREETING
_GREETEVERYONEREQUEST.fields_by_name['greeting'].message_type = _GREETING
DESCRIPTOR.message_types_by_name['Greeting'] = _GREETING
DESCRIPTOR.message_types_by_name['GreetRequest'] = _GREETREQUEST
DESCRIPTOR.message_types_by_name['GreetResponse'] = _GREETRESPONSE
DESCRIPTOR.message_types_by_name['GreetManyTimesRequest'] = _GREETMANYTIMESREQUEST
DESCRIPTOR.message_types_by_name['GreetManyTimesResponse'] = _GREETMANYTIMESRESPONSE
DESCRIPTOR.message_types_by_name['LongGreetRequest'] = _LONGGREETREQUEST
DESCRIPTOR.message_types_by_name['LongGreetResponse'] = _LONGGREETRESPONSE
DESCRIPTOR.message_types_by_name['GreetEveryoneRequest'] = _GREETEVERYONEREQUEST
DESCRIPTOR.message_types_by_name['GreetEveryoneResponse'] = _GREETEVERYONERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Greeting = _reflection.GeneratedProtocolMessageType('Greeting', (_message.Message,), {
  'DESCRIPTOR' : _GREETING,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:protos.Greeting)
  })
_sym_db.RegisterMessage(Greeting)

GreetRequest = _reflection.GeneratedProtocolMessageType('GreetRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:protos.GreetRequest)
  })
_sym_db.RegisterMessage(GreetRequest)

GreetResponse = _reflection.GeneratedProtocolMessageType('GreetResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETRESPONSE,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:protos.GreetResponse)
  })
_sym_db.RegisterMessage(GreetResponse)

GreetManyTimesRequest = _reflection.GeneratedProtocolMessageType('GreetManyTimesRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETMANYTIMESREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:protos.GreetManyTimesRequest)
  })
_sym_db.RegisterMessage(GreetManyTimesRequest)

GreetManyTimesResponse = _reflection.GeneratedProtocolMessageType('GreetManyTimesResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETMANYTIMESRESPONSE,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:protos.GreetManyTimesResponse)
  })
_sym_db.RegisterMessage(GreetManyTimesResponse)

LongGreetRequest = _reflection.GeneratedProtocolMessageType('LongGreetRequest', (_message.Message,), {
  'DESCRIPTOR' : _LONGGREETREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:protos.LongGreetRequest)
  })
_sym_db.RegisterMessage(LongGreetRequest)

LongGreetResponse = _reflection.GeneratedProtocolMessageType('LongGreetResponse', (_message.Message,), {
  'DESCRIPTOR' : _LONGGREETRESPONSE,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:protos.LongGreetResponse)
  })
_sym_db.RegisterMessage(LongGreetResponse)

GreetEveryoneRequest = _reflection.GeneratedProtocolMessageType('GreetEveryoneRequest', (_message.Message,), {
  'DESCRIPTOR' : _GREETEVERYONEREQUEST,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:protos.GreetEveryoneRequest)
  })
_sym_db.RegisterMessage(GreetEveryoneRequest)

GreetEveryoneResponse = _reflection.GeneratedProtocolMessageType('GreetEveryoneResponse', (_message.Message,), {
  'DESCRIPTOR' : _GREETEVERYONERESPONSE,
  '__module__' : 'rpc_pb2'
  # @@protoc_insertion_point(class_scope:protos.GreetEveryoneResponse)
  })
_sym_db.RegisterMessage(GreetEveryoneResponse)


DESCRIPTOR._options = None

_GREETSERVICE = _descriptor.ServiceDescriptor(
  name='GreetService',
  full_name='protos.GreetService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=455,
  serialized_end=761,
  methods=[
  _descriptor.MethodDescriptor(
    name='Greet',
    full_name='protos.GreetService.Greet',
    index=0,
    containing_service=None,
    input_type=_GREETREQUEST,
    output_type=_GREETRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GreetManyTimes',
    full_name='protos.GreetService.GreetManyTimes',
    index=1,
    containing_service=None,
    input_type=_GREETMANYTIMESREQUEST,
    output_type=_GREETMANYTIMESRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='LGreet',
    full_name='protos.GreetService.LGreet',
    index=2,
    containing_service=None,
    input_type=_LONGGREETREQUEST,
    output_type=_LONGGREETRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GreetEveryone',
    full_name='protos.GreetService.GreetEveryone',
    index=3,
    containing_service=None,
    input_type=_GREETEVERYONEREQUEST,
    output_type=_GREETEVERYONERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETSERVICE)

DESCRIPTOR.services_by_name['GreetService'] = _GREETSERVICE

# @@protoc_insertion_point(module_scope)
